Executer: Fix a link error for 64-bit division in the Debug object timestamp generation.
ACPICA should not use 64-bit division directly. This triggers the following
build error on Linux i386 kernel builds:
  drivers/built-in.o: In function `acpi_ex_do_debug_object':
  (.text+0x4e1a4): undefined reference to `__udivdi3'

This is introduced by the following commit:
  Commit: a4060d7fcfffff15a3e1d3aee7ccfd5cf00b50a0
  Subject: Debug object: Add current value of Timer() to debug line prefix.

Since the following 2 statements are equivalent as 0x03FFFFFF masking
keeps lower bits of num/12, and num/10 should have contained all valid bits
for 0x03FFFFFF masking no matter whether num is 32-bit or 64-bit:
 (UINT32) (num64 / 10) & 0x03FFFFFF;
 ((UINT32) num64 / 10) & 0x03FFFFFF;
This patch fixes this using the latter form statement to avoid 64-bit
division. Lv Zheng.

Signed-off-by: Lv Zheng <lv.zheng@intel.com>