linuxize: cut commit ID now has conflicts breaking linuxize process
Following error can be seen in linuxize process:
  error: short SHA1 07630ad9 is ambiguous.
  error: short SHA1 07630ad9 is ambiguous.
  fatal: ambiguous argument '07630ad9': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions
Fixing this by stop cutting commit IDs into 8-digits.

Signed-off-by: Lv Zheng <lv.zheng@intel.com>